### ISSUE TITLE
SQLAlchemy issue?

### ISSUE THREAD

**Issue by timmy-mac** [ubc/compair#649]
Hi there,

Firstly, thanks for open sourcing this - it'll be a great step forwards for assessment in a number of subjects if I can get any level of adoption in our organisation (UK secondary school).

I'm struggling to get it running on a Debian server at the moment and wondered if anyone has any pointers. I'm not sure if it's a Compair, SQLAlchemy or Debian issue really (Science teacher, not network admin!).

I'm following this: https://github.com/ubc/compair/tree/master/deploy/linux_server#deploying-compair-on-a-centos-7-server

..and all is well until: 

```
(.env) root@mail:/var/www/compair# DATABASE_URI=mysql+pymysql://compair:xxxxxxxxxxx@localhost/compair python manage.py database create
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from compair.manage.database import manager as database_manager
  File "/var/www/compair/compair/__init__.py", line 21, in <module>
    from compair.xapi import capture_xapi_events
  File "/var/www/compair/compair/compair/__init__.py", line 13, in <module>
    from .authorization import define_authorization
  File "/var/www/compair/compair/compair/authorization.py", line 9, in <module>
    from .models import Course, User, UserCourse, CourseRole, SystemRole, \
  File "/var/www/compair/compair/compair/models/__init__.py", line 10, in <module>
    from .activity_log import ActivityLog
  File "/var/www/compair/compair/compair/models/activity_log.py", line 9, in <module>
    class ActivityLog(DefaultTableMixin):
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 609, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 395, in _setup_table
    **table_kw)
  File "/var/www/compair/.env/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 422, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'activity_log' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.


```

Any thoughts greatly appreciated.

Tim

**Comment by timmy-mac** [comment]
I've got it working - well, I've crossed this bridge anyway!

I wish I could tell you for sure what I did differently but I think I'm now using the system version of sqlalchemy rather than the one installed in the virtualenv by pip.  I could be wrong!

**Comment by xcompass** [comment]
Glad to see others are using it. Let us know if you have any feedback. Feel free to post them on the google groups: https://groups.google.com/forum/#!forum/compair
